force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Custom object to capture invoices made from orders.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A lookup relationship to the Order object to link the invoice to the corresponding order.</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <description>Object to track invoice&apos;s line items.</description>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>II-{0000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>A master-detail relationship to the Invoice object, to ensure that line items are tied to a specific invoice.</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <description>Date when the invoice item is generated.</description>
    <label>Invoice Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A lookup relationship to the Order Product object to link the line item to a specific product.</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceGeneratorController.cls
/**
* InvoiceGeneratorController
* Controller for the invoiceGenerator Lightning web component.
*
* @author  Martín Messina
* @date   02-03-2024
*/

public with sharing class InvoiceGeneratorController {

    @AuraEnabled(cacheable=true)
    public static Integer getOrderItemsCount(Id orderId){
        // Returns the total of Order Items stored in the database.
        return [
            SELECT COUNT()
            FROM OrderItem
            WHERE OrderId = :orderId
            WITH SECURITY_ENFORCED
        ];
    }

    @AuraEnabled(cacheable=true) 
    public static List<OrderItem> getOrderItems(CustomWrapper wrapper){
        // Fetches OrderItems using the Order Id obtained from the current context.
        return [
            SELECT
            Product2.Name,
            UnitPrice,
            Quantity,
            TotalPrice
            FROM OrderItem
            WHERE OrderId = :wrapper.orderId
            WITH SECURITY_ENFORCED
            ORDER BY Product2.Name ASC
            LIMIT :wrapper.pageRecords
            OFFSET :wrapper.pageOffset
        ];
    }

    @AuraEnabled
    public static Id createInvoice(List<OrderItem> orderItems){
        // Creates Invoice and related Invoice Line Items from OrderItems.
        try {
            // Assigning Order Id.
            Id orderId = orderItems[0].OrderId;

            // Create Invoice
            Invoice__c invoice = new Invoice__c(
                Order__c = orderId
            );

            // Validate CRUD permissions
            if(Schema.sObjectType.Invoice__c.isCreateable()) {
                insert invoice;
            }
            else{
                throw new SecurityException(
                    'Insufficient permissions to create Invoices'
                );
            }

            List<InvoiceItem__c> invoiceItems = new List<InvoiceItem__c>();   

            for(OrderItem orderItem:orderItems){
                // Populates InvoiceItem__c new object to default values.

                InvoiceItem__c invoiceItem = (InvoiceItem__c)InvoiceItem__c.SObjectType.newSObject(null, true);
                
                invoiceItem.InvoiceDate__c = orderItem.ServiceDate;
                invoiceItem.OrderItem__c = orderItem.Id;
                invoiceItem.Invoice__c = invoice.Id;

                invoiceItems.add(invoiceItem);
            }

            if(Schema.sObjectType.InvoiceItem__c.isCreateable()) {
                insert invoiceItems;
            }
            else{
                throw new SecurityException(
                    'Insufficient permissions to create Invoice Line Items'
                );
            }

            return invoice.Id;
        } catch (Exception e) {
            throw newMessageException(e.getMessage());
        }
    }

    private static AuraHandledException newMessageException(String message) {
        AuraHandledException e = new AuraHandledException(message);
        e.setMessage(message);
        return e;
    }
}